baseURL = "http://example.org/"
languageCode = "en-us"
theme = "ananke"
title = "My New Hugo Site"
[[menu.main]]
name = "Posts"
pre = "<i class='fa fa-road'></i>"
url = "/posts/"
weight = 2
[[menu.main]]
name = "getting started"
pre = "<i class='fa fa-road'></i>"
url = "/getting-started/"
weight = 3
[[menu.main]]
identifier = "about"
name = "about hugo"
pre = "<i class='fa fa-heart'></i>"
url = "/about/"
weight = 1
